name: Deploy to github pages branch
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '13.x'
      - run: yarn install
      - run: yarn build:en
      - run: yarn build:jp
      - run: ./node_modules/now/dist/index.js enOut --prod --name y-combinator-for-non-programmers-en --token=${{ secrets.ZEIT_EN_TOKEN }}
      - run: ./node_modules/now/dist/index.js jpOut --prod --name y-combinator-for-non-programmers-jp --token=${{ secrets.ZEIT_JP_TOKEN }}
