name: Deploy to github pages branch
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '13.x'
      - run: yarn install
      - run: yarn build:en
      - uses: peaceiris/actions-gh-pages@v2.5.0
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: en
          PUBLISH_DIR: ./enOut
      - run: yarn build:jp
      - uses: peaceiris/actions-gh-pages@v2.5.0
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: jp
          PUBLISH_DIR: ./jpOut
      - run: git checkout en
      - run: ./node_modules/now/dist/index.js --prod --name y-combinator-for-non-programmers-en --token=${{ secrets.ZEIT_EN_TOKEN }}
      - run: git checkout jp
      - run: ./node_modules/now/dist/index.js --prod --name y-combinator-for-non-programmers-jp --token=${{ secrets.ZEIT_JP_TOKEN }}
